/*

 ENEMIES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define enemiesBank 0

/* Super Gameboy palette 0 */
#define enemiesSGBPal0c0 6076
#define enemiesSGBPal0c1 8935
#define enemiesSGBPal0c2 6596
#define enemiesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define enemiesSGBPal1c0 6076
#define enemiesSGBPal1c1 8935
#define enemiesSGBPal1c2 6596
#define enemiesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define enemiesSGBPal2c0 6076
#define enemiesSGBPal2c1 8935
#define enemiesSGBPal2c2 6596
#define enemiesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define enemiesSGBPal3c0 6076
#define enemiesSGBPal3c1 8935
#define enemiesSGBPal3c2 6596
#define enemiesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define enemiesCGBPal0c0 6076
#define enemiesCGBPal0c1 8935
#define enemiesCGBPal0c2 6596
#define enemiesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define enemiesCGBPal1c0 6076
#define enemiesCGBPal1c1 8935
#define enemiesCGBPal1c2 6596
#define enemiesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define enemiesCGBPal2c0 6076
#define enemiesCGBPal2c1 8935
#define enemiesCGBPal2c2 6596
#define enemiesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define enemiesCGBPal3c0 6076
#define enemiesCGBPal3c1 8935
#define enemiesCGBPal3c2 6596
#define enemiesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define enemiesCGBPal4c0 6076
#define enemiesCGBPal4c1 8935
#define enemiesCGBPal4c2 6596
#define enemiesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define enemiesCGBPal5c0 6076
#define enemiesCGBPal5c1 8935
#define enemiesCGBPal5c2 6596
#define enemiesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define enemiesCGBPal6c0 6076
#define enemiesCGBPal6c1 8935
#define enemiesCGBPal6c2 6596
#define enemiesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define enemiesCGBPal7c0 6076
#define enemiesCGBPal7c1 8935
#define enemiesCGBPal7c2 6596
#define enemiesCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char enemies[];

/* End of ENEMIES.H */
