/*

 POWERUPS_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : C:\Users\GilDurao\Documents\gbtd22\powerups.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define powersup_mapWidth 10
#define powersup_mapHeight 1
#define powersup_mapBank 0

unsigned char powersup_map[] =
{
  0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09
};

/* End of POWERUPS_MAP.C */
