/*

 SAMPLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 256 x 19
   Tile set      : Z:\home\joao\Documents\gamejam\GB\gbdk\games\ludum-dare-2021\assets\tiles\levelOne.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define sample_mapWidth 256
#define sample_mapHeight 19
#define sample_mapBank 0

extern unsigned char sample_map[];

/* End of SAMPLEMAP.H */
