/*

 LETTERS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 9

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define lettersBank 0

/* Super Gameboy palette 0 */
#define lettersSGBPal0c0 6076
#define lettersSGBPal0c1 8935
#define lettersSGBPal0c2 6596
#define lettersSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define lettersSGBPal1c0 6076
#define lettersSGBPal1c1 8935
#define lettersSGBPal1c2 6596
#define lettersSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define lettersSGBPal2c0 6076
#define lettersSGBPal2c1 8935
#define lettersSGBPal2c2 6596
#define lettersSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define lettersSGBPal3c0 6076
#define lettersSGBPal3c1 8935
#define lettersSGBPal3c2 6596
#define lettersSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define lettersCGBPal0c0 6076
#define lettersCGBPal0c1 8935
#define lettersCGBPal0c2 6596
#define lettersCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define lettersCGBPal1c0 6076
#define lettersCGBPal1c1 8935
#define lettersCGBPal1c2 6596
#define lettersCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define lettersCGBPal2c0 6076
#define lettersCGBPal2c1 8935
#define lettersCGBPal2c2 6596
#define lettersCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define lettersCGBPal3c0 6076
#define lettersCGBPal3c1 8935
#define lettersCGBPal3c2 6596
#define lettersCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define lettersCGBPal4c0 6076
#define lettersCGBPal4c1 8935
#define lettersCGBPal4c2 6596
#define lettersCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define lettersCGBPal5c0 6076
#define lettersCGBPal5c1 8935
#define lettersCGBPal5c2 6596
#define lettersCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define lettersCGBPal6c0 6076
#define lettersCGBPal6c1 8935
#define lettersCGBPal6c2 6596
#define lettersCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define lettersCGBPal7c0 6076
#define lettersCGBPal7c1 8935
#define lettersCGBPal7c2 6596
#define lettersCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char letters[];

/* End of LETTERS.H */
