/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 43 x 40
   Tile set      : C:\Users\GilDurao\Documents\gbtd22\letters.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define titleMapWidth 43
#define titleMapHeight 40
#define titleMapBank 0

extern unsigned char titleMap[];

/* End of MAP.H */
